apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: Publish a messsage to an SNS topic.
    workflows.argoproj.io/maintainer: '@masonkmeyer'
    workflows.argoproj.io/tags: aws,sns,notification
    workflows.argoproj.io/version: '>= 2.9.0'
  name: aws-sns-notification
spec:
  arguments:
    parameters:
    - name: topic_arn
      valueFrom:
        supplied: {} 
    - name: message
      valueFrom:
        supplied: {}
    - name: region 
      valueFrom:
        supplied: {}                
  entrypoint: publish-sns
  templates:
    - name: publish-sns
      inputs:
        parameters:
          - name: topic_arn
          - name: message
          - name: region
      container:
        imagePullPolicy: IfNotPresent
        image: amazon/aws-cli:latest
        env:
          - name: AWS_REGION
            value: "{{inputs.parameters.region}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_SECRET_ACCESS_KEY
        command: ["aws"]
        args:
          - sns
          - publish
          - "--topic-arn"
          - "{{inputs.parameters.topic_arn}}"
          - "--message"
          - "{{inputs.parameters.message}}"
